export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const UPDATE = 'UPDATE';

export const AUTHENTICATE = 'AUTHENTICATE';
export const BEARER_AUTHENTICATE = 'BEARER_AUTHENTICATE';
export const BEARER_AUTHENTICATION_REQUEST = 'BEARER_AUTHENTICATION_REQUEST';
export const BEARER_AUTHENTICATION_FAILURE = 'BEARER_AUTHENTICATION_FAILURE';
export const LOGOUT = 'LOGOUT';

export const SET_USERNAME = 'SET_USERNAME';

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const FETCH_USER_DETAILS_REQUEST = 'FETCH_USER_DETAILS_REQUEST';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_FAILURE = 'FETCH_USER_DETAILS_FAILURE';
