export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const UPDATE = 'UPDATE';

export const AUTHENTICATE = 'AUTHENTICATE';
export const BEARER_AUTHENTICATE = 'BEARER_AUTHENTICATE';
export const BEARER_AUTHENTICATION_REQUEST = 'BEARER_AUTHENTICATION_REQUEST';
export const BEARER_AUTHENTICATION_FAILURE = 'BEARER_AUTHENTICATION_FAILURE';
export const LOGOUT = 'LOGOUT';

export const SET_USERNAME = 'SET_USERNAME';

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const FETCH_USER_DETAILS_REQUEST = 'FETCH_USER_DETAILS_REQUEST';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_FAILURE = 'FETCH_USER_DETAILS_FAILURE';

export const UPDATE_VERIFICATION_DETAILS = 'UPDATE_VERIFICATION_DETAILS';

export const VERIFY_PI_REQUEST = 'VERIFY_PI_REQUEST';
export const VERIFY_PI_SUCCESS = 'VERIFY_PI_SUCCESS';
export const VERIFY_PI_FAILURE = 'VERIFY_PI_FAILURE';

export const FETCH_STATS_DEVICES_SUCCESS = 'FETCH_STATS_DEVICES_SUCCESS';

export const FETCH_STATS_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_VERIFICATIONS_REQUEST = 'FETCH_VERIFICATIONS_REQUEST';
export const FETCH_VERIFICATIONS_SUCCESS = 'FETCH_VERIFICATIONS_SUCCESS';
export const FETCH_VERIFICATIONS_FAILURE = 'FETCH_VERIFICATIONS_FAILURE';

export const CLEAR_VERIFICATION_RESULT = 'CLEAR_VERIFICATION_RESULT';
export const CLEAR_VERIFICATION_DETAILS = 'CLEAR_VERIFICATION_DETAILS';

export const SORT_DATE_SUCCESS = 'SORT_DATE_SUCCESS';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAILURE = 'PRODUCT_DETAILS_FAILURE';

export const UPDATE_DEVICE_TYPE = 'UPDATE_DEVICE_TYPE';
